name: Installer action
   
on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      container_name:
        required: false
        type: string
        default: ""
      artifact_name:
        required: true
        type: string
jobs:
  job:
    defaults:
      run:
        shell: bash

    runs-on: ${{ inputs.os }}
    container: ${{ inputs.container_name }}
    
    steps:
    - name: Download installer artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifact_name }}
      
    - name: Install trik-studio
      run: |
        INSTALLER_NAME=$(ls -1d $GITHUB_WORKSPACE/*installer | head -n 1)
        UNINSTALL_SCRIPT_PATH=$GITHUB_WORKSPACE/trik_studio_uninstallscript.qs \
        $INSTALLER_NAME --script trik_studio_installscript.qs
       
    - name: Downloads minimal tests
      run: |
      	curl --output tests.7z "https://dl.trikset.com/edu/.solutions20200701/testing_small.7z"
        7za x tests.7z
        
    - name: Run minimal tests
        TWOD_EXEC_NAME=$(ls -1d $GITHUB_WORKSPACE/2D-model* | head -n 1)
        for i in $GITHUB_WORKSPACE/testing_small/*; do "$TWOD_EXEC_NAME" -b "$i"; done
       
    
